---
- hosts: myservers
  become: yes
  tasks:
    - name: install nginx on Rocky
      yum:
        name: nginx
        state: latest
      when: ansible_os_family == "RedHat"

    - name: install nginx on Ubuntu
      apt:
        name: nginx
        state: latest
      when: ansible_os_family == "Debian"
    