---
- name: Simple example of Ansible handlers
  hosts: myservers
  become: yes
  tasks:

    - name: Ensure nginx package is present
      yum:
        name: nginx
        state: latest
      notify: restart_nginx

  handlers:

    - name: restart_nginx
      service:
        name: nginx
        state: restarted
