---
- name: Copy nginx file to remote servers
  hosts: myservers
  become: yes

  tasks:
    - name: Copy nginx file
      copy:
        src: 06_playbook1-index.html
        dest: /var/www/nginx-default/index.html
